### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by aghecenco** [rust-vmm/linux-loader#18]
Before this crate is published, the following issues need to be fixed:
- [x] #15: design / code structuring flaw. `linux-loader` is not fully independent while it relies on external interactions for writing bootparams.
- [x] #12: bug.
- [x] #19: `aarch64` support.
- [x] #17: documentation needs to be extensive.
- [x] #20: rework code organization.
- [x] #22: refactor per arch and feature.
- [x] #21: aim for 100% coverage :rocket: 
- [x] #40: performance tests

The list is open.

**Comment by aghecenco** [comment]
Req list here: https://github.com/rust-vmm/community#publishing-on-cratesio---requirements-list

**Comment by aghecenco** [comment]
https://crates.io/crates/linux-loader
